Added testssl attack
myOmikron/kraken-project pull request #148
Opened 2024-01-22 16:05 UTC by gammelalf

2024-01-24 13:17 UTC, myOmikron requested changes

2024-01-24 13:17 UTC, myOmikron commented on kraken-proto/src/convert.rs
> +    InvalidMitreTechnique(u32, u32),
I'd inline the parameters:
```rs
    #[error("Got unknown mitre att&ck tactic: TA{0:04}")]

    #[error("Got unknown mitre att&ck technique: T{1:04} (for TA{0:04})")]
```

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/attacks/schema.rs
> +    #[schema(value_type = String)]
provide an example, so that swagger doesn't show an empty string

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/attack_results/schema.rs
> +    pub ip: String,
Use IpAddr with swagger annotations

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/attack_results/schema.rs
> +    /// The original user target this result belongs to
Rework english

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/models/attack/mod.rs
> +}
Will be implemented by upstream

2024-01-24 13:17 UTC, myOmikron commented on leech/src/modules/testssl/mod.rs
> +}
Inline parameter:
```rs
    #[error("Io error: {0}")]
```

2024-01-24 13:17 UTC, myOmikron commented on kraken-proto/src/mitre.rs
No necessary

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/aggregation_source/utils.rs
> +                                    ip: result.ip.ip().to_string(),
IpAddr should be used in API

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/attack_results/handler.rs
> +        ip: header.ip.ip().to_string(),
IpAddr should be used in API

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/modules/attacks/testssl.rs
> +                };
Check for 0

2024-01-24 13:17 UTC, myOmikron commented on kraken/src/api/handler/attacks/handler.rs
> +    let (attack_uuid, _) = start_testssl(
Check for 0 port

2024-01-24 15:33 UTC, gammelalf commented on kraken/src/api/handler/attack_results/schema.rs
> +    pub ip: String,
Its not an ip

2024-01-25 19:26 UTC, myOmikron approved these changes

2024-09-06 09:29 UTC, myOmikron requested changes
TODO!

2024-09-06 09:29 UTC, myOmikron commented on kraken/src/models/attack/mod.rs
> +    // TODO: shouldn't this be associated with the header?
TODO!

2024-09-06 09:29 UTC, myOmikron commented on kraken_frontend/src/api/api.ts
> +        impl: attacks, // TODO add testssl
TODO!

2024-09-12 10:04 UTC, myOmikron approved these changes

2024-09-12 10:05 UTC, merged